name: WaledNet
description: "WaledNet VPN - sing-box powered"
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.3.0
  provider: ^6.1.5+1
  http: ^1.4.0
  google_fonts: ^8.1.0
  url_launcher: ^6.2.6
  cupertino_icons: ^1.0.9
  package_info_plus: ^10.2.0
  shared_preferences: ^2.5.5
  path_provider: ^2.1.3
  dio: ^5.9.2
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.4
  firebase_messaging: ^16.4.1
  unity_ads_plugin: ^0.4.0
  crypto: ^3.0.3
  dartssh2: ^2.22.0
  in_app_purchase: ^3.3.0
  google_sign_in: 7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
